[[config]]
    [[config.gpu_config]]
    vendor_id = 0x10DE
    [[config.request]]
    num = 1
    max_instances = 10
    fb_len = 896
    fb_res = 128
    name = "GVM [Geforce /10]"
    class = "Geforce"
    v_dev_id = 0x1B301B30
    ecc_support = true
    enc_cap = 100
    map_video_size = 4
    bar1_len = 0x100
        [config.request.display]
        num_heads = 4
        max_res_x = 3840
        max_res_y = 2160
        frl_config = 120
        frl_enable = 1
    [[config.request]]
    num = 2
    max_instances = 10
    fb_len = 896
    fb_res = 128
    name = "GVM [NVS /10]"
    class = "NVS"
    v_dev_id = 0x1B301B30
    ecc_support = true
    enc_cap = 100
    map_video_size = 4
    bar1_len = 0x100
        [config.request.display]
        num_heads = 4
        max_res_x = 3840
        max_res_y = 2160
        frl_config = 120
        frl_enable = 1
    [[config.request]]
    num = 3
    max_instances = 10
    fb_len = 896
    fb_res = 128
    name = "GVM [Quadro /10]"
    class = "Quadro"
    v_dev_id = 0x1B301B30
    ecc_support = true
    enc_cap = 100
    map_video_size = 4
    bar1_len = 0x100
        [config.request.display]
        num_heads = 4
        max_res_x = 3840
        max_res_y = 2160
        frl_config = 120
        frl_enable = 1
