[[config]]
    [[config.gpu_config]]
    vendor_id = 0x10DE

    [[config.request]]
    num = 23
    v_dev_id = 0x233116DE
    p_dev_id = 0x2330
    name = "GVM GPU"
    class = "Compute"
    fb_len = 39000
    max_instances = 1
    ecc = False
    multi_mdev = False
    fb_res = 1536
    map_video_size = 4
    enc_cap = 100
    bar1_len = 0x100
        [config.request.display]
        num_heads = 1
        max_res_x = 3840
        max_res_y = 2160
