[[config]]
    [[config.gpu_config]]
    vendor_id = 0x10DE

    [[config.request]]
    num = 22
    v_dev_id = 0x1B301B30
    p_dev_id = 0x1B30
    name = "GVM GPU"
    class = "Quadro"
    fb_len = 896
    max_instances = 1
    ecc = False
    multi_mdev = False
    fb_res = 128
    map_video_size = 4
    enc_cap = 100
    bar1_len = 0x100
        [config.request.display]
        max_res_x = 3840
        max_res_y = 2160
